[project]
name = "mcpnp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.13.1",
    "httpx>=0.25.0",
    "mcp-use>=1.3.10",
    "langchain-groq>=0.3.7",
]
